# Generated by Django 5.0.6 on 2024-06-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='owner_contact',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
