# Generated by Django 5.0.6 on 2024-06-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('car_name', models.CharField(max_length=200)),
                ('payment_price', models.FloatField()),
                ('description', models.TextField()),
                ('img', models.FileField(upload_to='static/uploads')),
            ],
        ),
    ]
