# Generated by Django 5.0.6 on 2024-06-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='interested_drivers',
            field=models.ManyToManyField(blank=True, related_name='interested_cars', to='driver.driverprofile'),
        ),
    ]
